# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, verbose_name='资产序列号')),
                ('asset_type', models.PositiveSmallIntegerField(choices=[(0, '物理机'), (1, '虚拟机'), (2, '交换机'), (3, '路由器'), (4, '其它设备')], default=1, verbose_name='资产类型')),
                ('os', models.CharField(max_length=50, verbose_name='操作系统')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机房名称')),
                ('address', models.CharField(max_length=200, verbose_name='机房地址')),
                ('contact_name', models.CharField(max_length=20, verbose_name='联系人姓名')),
                ('contact_phone', models.PositiveIntegerField(max_length=11, verbose_name='联系人电话')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20, verbose_name='IP地址')),
                ('is_used', models.BooleanField(verbose_name='是否已使用')),
            ],
            options={
                'verbose_name': 'IP地址',
                'verbose_name_plural': 'IP地址',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=100, verbose_name='用途')),
                ('subnet', models.CharField(max_length=20, verbose_name='子网')),
                ('netmask', models.PositiveSmallIntegerField(verbose_name='网络掩码')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Idc')),
            ],
            options={
                'verbose_name': '网络',
                'verbose_name_plural': '网络',
            },
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Network'),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IpAddress', verbose_name='IP 地址'),
        ),
    ]
