# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='资产分组')),
                ('common', models.CharField(max_length=200, verbose_name='分组描述')),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idc',
            name='contact_phone',
            field=models.PositiveIntegerField(verbose_name='联系人电话'),
        ),
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ManyToManyField(to='cmdb.AssetGroup', verbose_name='资产分组'),
        ),
    ]
