# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20171204_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetgroup',
            options={'verbose_name': '资产分组', 'verbose_name_plural': '资产分组'},
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='是否是vip'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='是否已使用'),
        ),
    ]
