# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20171206_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
