# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_network_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['-ip_address'], 'verbose_name': 'IP地址', 'verbose_name_plural': 'IP地址'},
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='is_used',
        ),
    ]
